version: '2'
services:
    pocsignaturit-app:
        image: pocsignaturit
        external_links:
            - pocsignaturit-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pocSignaturit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pocsignaturit-postgresql:
        extends:
            file: postgresql.yml
            service: pocsignaturit-postgresql
